<a href="https://colab.research.google.com/github/daksh-pote/MAL/blob/main/DigitRecognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DIGIT RECOGNITION PROJECT


In [2]:
# importing libraries
# git changes

In [3]:
import pandas as pd
import numpy as np

In [4]:
from keras import datasets

In [11]:
(x_train, y_train),(x_test, y_test) = datasets.mnist.load_data()

In [12]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [13]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [14]:
x_train.shape

(60000, 28, 28)

In [15]:
x_test.shape

(10000, 28, 28)

RESHAPING DATA / FEATURE SCALING

In [17]:
width, height = 28, 28
input_shape = (width, height, 1)

In [18]:
input_shape

(28, 28, 1)

In [19]:
x_train = x_train.reshape(x_train.shape[0], width, height, 1)
x_test = x_test.reshape(x_test.shape[0], width, height, 1)

In [20]:
x_train.shape

(60000, 28, 28, 1)

In [21]:
y_train.shape

(60000,)

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1)

In [23]:
len(x_val)

6000

NORMALIZING DATA

In [24]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [25]:
x_train

array([[[[-0.42406214],
         [-0.42406214],
         [-0.42406214],
         ...,
         [-0.42406214],
         [-0.42406214],
         [-0.42406214]],

        [[-0.42406214],
         [-0.42406214],
         [-0.42406214],
         ...,
         [-0.42406214],
         [-0.42406214],
         [-0.42406214]],

        [[-0.42406214],
         [-0.42406214],
         [-0.42406214],
         ...,
         [-0.42406214],
         [-0.42406214],
         [-0.42406214]],

        ...,

        [[-0.42406214],
         [-0.42406214],
         [-0.42406214],
         ...,
         [-0.42406214],
         [-0.42406214],
         [-0.42406214]],

        [[-0.42406214],
         [-0.42406214],
         [-0.42406214],
         ...,
         [-0.42406214],
         [-0.42406214],
         [-0.42406214]],

        [[-0.42406214],
         [-0.42406214],
         [-0.42406214],
         ...,
         [-0.42406214],
         [-0.42406214],
         [-0.42406214]]],


       [[[-0.42406214],


In [26]:
y_train

array([9, 4, 0, ..., 6, 2, 1], dtype=uint8)

In [27]:
from tensorflow import keras

In [28]:
y_train

array([9, 4, 0, ..., 6, 2, 1], dtype=uint8)

In [29]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

In [30]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

MODEL

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, AveragePooling2D, MaxPooling2D, Dropout, Input

LeNET-5 architecture

In [34]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5,5), strides = (1,1), activation = 'tanh', input_shape = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5,5), strides = (1,1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2,2), strides = (2,2)))
model.add(Conv2D(120, kernel_size = (5,5), strides = (1,1), activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))


In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (Average  (None, 23, 23, 6)         0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Avera  (None, 9, 9, 16)          0         
 gePooling2D)                                                    
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten (Flatten)           (None, 3000)              0

TRAINING MODEL

In [38]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [40]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 5, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/5
1688/1688 [==============================] - 57s 34ms/step - loss: 0.0601 - accuracy: 0.9819 - val_loss: 0.0747 - val_accuracy: 0.9763
Epoch 2/5
1688/1688 [==============================] - 56s 33ms/step - loss: 0.0559 - accuracy: 0.9826 - val_loss: 0.0641 - val_accuracy: 0.9808
Epoch 3/5
1688/1688 [==============================] - 57s 34ms/step - loss: 0.0526 - accuracy: 0.9834 - val_loss: 0.0576 - val_accuracy: 0.9827
Epoch 4/5
1688/1688 [==============================] - 61s 36ms/step - loss: 0.0507 - accuracy: 0.9851 - val_loss: 0.0685 - val_accuracy: 0.9798
Epoch 5/5
1688/1688 [==============================] - 60s 36ms/step - loss: 0.0511 - accuracy: 0.9843 - val_loss: 0.0647 - val_accuracy: 0.9787


TESTING MODEL

In [41]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 [==============================] - 3s 10ms/step - loss: 0.0568 - accuracy: 0.9827


In [42]:
score

[0.05679267644882202, 0.982699990272522]